flowchart_data <-
  tibble::tibble(id = c(1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19),
                 question = c("Fixed resources?",
                              "Test what you can afford",
                              "Inferential goal",
                              "Expected effect size",
                              "Statistical framework",
                              "TOST",
                              "Interval equiv Bf",
                              "Statistical framework",
                              "Range of effects?",
                              "Traditional power",
                              "Power curve",
                              "Sequential testing?",
                              "BFDA",
                              "Bf threshold",
                              "Statistical framework",
                              "Population SD known?",
                              "AIPE",
                              "APP",
                              "ROPE"),
                 is_method = c(0L,
                               0L,
                               0L,
                               0L,
                               0L,
                               1L,
                               1L,
                               0L,
                               0L,
                               1L,
                               1L,
                               0L,
                               1L,
                               1L,
                               0L,
                               0L,
                               1L,
                               1L,
                               1L),
                 glossary = c("",
                              "",
                              "",
                              "",
                              "",
                              "It is an equivalence testing approach for two-sided t-tests.",
                              "short text about interval equiv Bf.",
                              "",
                              "",
                              "This general approach indicates the long-term error rate of rejecting the null hypothesis for the observed or more extreme parameters in a given design when the model assumptions (e.g., independence of observations) are true.",
                              "This curve shows how changes in effect size or sample size modify the statistical power of a test.",
                              "",
                              "This technique estimates the long-term rates of misleading evidence that one can expect for a specific research design if using preset Bayes Factor thresholds.",
                              "Short text about Bf threshold",
                              "",
                              "",
                              "A sample size estimation method used for parameter estimation. The approach aims to narrow down the width of the confidence interval in order to increase the accuracy of the estimated parameter.",
                              "The approach aims to plan a sample size based on how close the researcher wishes the sample parameter to be to the population parameter, and how confident the researcher wants to be in this.",
                              "It is a region of sample sizes that a Bayesian analyst can regard of negligible magnitude for practical purposes."))

usethis::use_data(flowchart_data, overwrite = TRUE)
