question_data <-
  tibble::tibble(id = c(1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17),
                 question = c("Do you have fixed resources?",
                              "You should test what you can afford.",
                              "What is you inferential goal?",
                              "What is your expected effect?",
                              "What statistical framework do you prefer?",
                              "TOST",
                              "ROPE",
                              "What statistical framework do you prefer?",
                              "Are you interested in a range of effects?",
                              "Traditional power",
                              "Power curve",
                              "Do you want to use sequential testing?",
                              "BFDA",
                              "Bf treshold",
                              "Is the population Standard Deviation known?",
                              "AIPE",
                              "APP"),
                 label_left = c("Yes",
                                "Next",
                                "Testing",
                                "=0",
                                "Frequentist",
                                NA_character_,
                                NA_character_,
                                "Frequentist",
                                "Single effect size",
                                NA_character_,
                                NA_character_,
                                "Yes",
                                NA_character_,
                                NA_character_,
                                "Yes",
                                NA_character_,
                                NA_character_),
                 label_right = c("No",
                                 NA_character_,
                                 "Estimation",
                                 ">0",
                                 "Bayesian",
                                 NA_character_,
                                 NA_character_,
                                 "Bayesian",
                                 "Range of effect sizes",
                                 NA_character_,
                                 NA_character_,
                                 "No",
                                 NA_character_,
                                 NA_character_,
                                 "No",
                                 NA_character_,
                                 NA_character_),
                 id_left = c(2,
                             3,
                             4,
                             5,
                             6,
                             NA_integer_,
                             NA_integer_,
                             9,
                             10,
                             NA_integer_,
                             NA_integer_,
                             13,
                             NA_integer_,
                             NA_integer_,
                             16,
                             NA_integer_,
                             NA_integer_),
                 id_right = c(3,
                              NA_integer_,
                              15,
                              8,
                              7,
                              NA_integer_,
                              NA_integer_,
                              12,
                              11,
                              NA_integer_,
                              NA_integer_,
                              14,
                              NA_integer_,
                              NA_integer_,
                              17,
                              NA_integer_,
                              NA_integer_),
                 is_method = c(0L,
                               0L,
                               0L,
                               0L,
                               0L,
                               1L,
                               1L,
                               0L,
                               0L,
                               1L,
                               1L,
                               0L,
                               1L,
                               1L,
                               0L,
                               1L,
                               1L))

usethis::use_data(question_data, overwrite = TRUE)
